title: Alejandro Barrientos
subtitle: Process Engineer - MSc. Data Science and Analytics
description: Machine Learning | Generative AI | MLOps | RAG | Data Engineering | Python | Math and Statistics | AWS | Leadership
remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: "dark"

# Disable RSS feed in footer
atom_feed:
  hide: true

# Reading Files
include:
  - _pages

# Site Author
author:
  name: "Alejandro Barrientos"
  avatar: "/assets/img/profile_pic.jpg"
  bio: "Process Engineer \n MSc. Data Science and Analytics"
  location: "Medell√≠n, Colombia"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:alejoba1097@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alejandro-barrientos/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alejoba1097"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:alejoba1097@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alejandro-barrientos/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alejoba1097"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
